id: A36388C66
title: Prayer for the Long Life of Dezhung Rinpoche
type: translation
pechas:
- I904D983F
- I7563FFD2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:10.083927
  last_modified_at: 2023-01-04 11:37:10.083939
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I904D983F/CCC3: 23C4
  I7563FFD2/E06E: 23C4
